spring:
  liquibase:
    change-log: classpath:db.changelog-master.xml

  h2:
    console:
      enabled: true

  datasource:
    url: "jdbc:postgresql://localhost:5433/postgres"
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver